In [36]:
import numpy as np
#from ucimlrepo import fetch_ucirepo 
import pandas as pd
import json
import os
#import torch
from scipy import optimize

In [1]:
import torch


In [15]:
np.set_printoptions(suppress=True, precision=5)

In [3]:
dataname_list = ["banknote","yeast","climate_model_crashes",
                 "wine_quality_white", "yacht_hydrodynamics","concrete_compression",
                 "breast_cancer","solar_fire","car_evluation"
                 ]

In [4]:
def save_split_index_cv(scaled_data, directory_path, seed=1, nfold=5):
    indlist = np.arange(len(scaled_data))

    np.random.seed(seed)
    np.random.shuffle(indlist)

    fold_size = len(scaled_data) // nfold
    save_index = {}

    for fold in range(nfold):
        start = fold * fold_size
        end = start + fold_size if fold < nfold - 1 else len(scaled_data)
        
        test_index = indlist[start:end]
        train_index = np.concatenate([indlist[:start], indlist[end:]])

        # If you want to split the training set into train and validation sets
        num_train = int(len(train_index) * 0.9)
        train_subindex = train_index[:num_train]
        valid_subindex = train_index[num_train:]

        fold_index = {
            "test_index": test_index.astype(np.int64).tolist(),
            "train_index": train_subindex.astype(np.int64).tolist(),
            "valid_index": valid_subindex.astype(np.int64).tolist()
        }
        save_index[f"fold_{fold+1}"] = fold_index

    with open(f"data/{directory_path}/split_index_cv_seed-{seed}_nfold-{nfold}.json", 'w') as file:
        json.dump(save_index, file)

In [9]:
def load_data(name):
    if name == "banknote":
        with open('data/banknote/data_banknote_authentication.txt', 'rb') as f:
            df = pd.read_csv(f, low_memory=False, sep=',',header = None)
            Xy = {}
            # Ignore the two blocking factor
            Xy['data'] = df.values[:, :-1]
            Xy['target'] =  df.values[:, -1]
    elif name == "yeast":
        with open('data/yeast/yeast.data', 'rb') as f:
            df = pd.read_csv(f, delimiter='\s+', header = None)
            Xy = {}
            # remove index
            Xy['data'] = df.values[:, 1:-1].astype('float')
            Xy['target'] =  df.values[:, -1]
    elif name == "climate_model_crashes":
        with open('data/climate_model_crashes/pop_failures.dat', 'rb') as f:
            df = pd.read_csv(f, delimiter='\s+', header = 0)
            Xy = {}
            # Ignore the two blocking factor
            Xy['data'] = df.values[:, 2:-1]
            Xy['target'] =  df.values[:, -1]
    elif name == "wine_quality_white":
        with open('data/wine_quality_white/data.csv', 'rb') as f:
            df = pd.read_csv(f, delimiter=';')
            Xy = {}
            Xy['data'] = df.values[:, :-1].astype('float')
            Xy['target'] =  df.values[:, -1]

    elif name == "yacht_hydrodynamics":
        with open('data/yacht_hydrodynamics/yacht_hydrodynamics.data', 'rb') as f:
            df = pd.read_csv(f, delimiter='\s+', header = None)
            Xy = {}
            Xy['data'] = df.values[:, :-1]
            Xy['target'] =  df.values[:, -1]

    elif name == "concrete_compression":
        with open('data/concrete_compression/Concrete_Data.xls', 'rb') as f:
            df = pd.read_excel(io=f)
            Xy = {}
            Xy['data'] = df.values[:, :-1]
            Xy['target'] =  df.values[:, -1]

    elif name == "breast_cancer":
        with open('data/breast_cancer/breast_cancer.data', 'rb') as f:
            df = pd.read_csv(f, delimiter=',', header = None)
            Xy = {}
            Xy['data'] = df.values[:, :-1]
            Xy['target'] =  df.values[:, -1]

    elif name == "solar_fire":
        with open('data/solar_fire/flare.data1', 'rb') as f:
            df1 = pd.read_csv(f, delimiter='\s+', header = None)
        with open('data/solar_fire/flare.data2', 'rb') as f:
            df2 = pd.read_csv(f, delimiter='\s+', header = None)
            df = pd.concat([df1, df2], ignore_index=True)
            Xy = {}
            Xy['data'] = df.values[:, :-1]
            Xy['target'] =  df.values[:, -1]

    elif name == "car_evaluation":
        with open('data/car_evaluation/car.data', 'rb') as f:
            df = pd.read_csv(f, delimiter=',', header = None)
            Xy = {}
            Xy['data'] = df.values[:, :-1]
            Xy['target'] =  df.values[:, -1]

    return Xy


In [163]:
dataname_list = ["banknote","yeast","climate_model_crashes",
                 "wine_quality_white", 
                 "yacht_hydrodynamics",
                 "concrete_compression",
                #  "breast_cancer",
                #  "solar_fire",
                #  "car_evaluation"
                 ]
save = True
p = 0.5

missing_rate = [0.05,0.1,0.3, 0.5]


#dataname_list = ["yeast"]
for name in dataname_list:
    
    print(name,p)
    Xy = load_data(name)
    
    feature = Xy['data']
    label = Xy['target']


    #
    #print("MNAR")
    for type in ["mcar","mar","mnar"]:
        print(type)
        if type == "mcar":
            mask = MCAR(feature, p, seed=1)
        elif type == "mar":
            mask = MAR(feature, p)
        elif type == "mnar":
            mask = MNAR(feature, p)

        for rate in missing_rate:
            #print(rate)
            mask_copy = mask.copy()
            mask_copy = mask_recover(mask_copy, rate)

            #calculate_missing_rates(mask_copy)

            if save:
                path = f"data/{name}/{type}"
                ensure_dir(path)
                np.save(f"{path}/{rate}.npy",mask_copy)
        print()
        
    

    if save:
        save_split_index_cv(Xy['data'],name,seed = 1,nfold = 5)
        np.save(f"data/{name}/feature.npy", Xy['data'])
        np.save(f"data/{name}/label.npy", Xy['target'])


banknote 0.5
mcar
[0.5 0.5 0.5 0.5] 0.5

mar

mnar
Missing Rate 0.5

yeast 0.5
mcar
[0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5] 0.5

mar

mnar
Missing Rate 0.5

climate_model_crashes 0.5
mcar
[0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5] 0.5

mar

mnar
Missing Rate 0.5

wine_quality_white 0.5
mcar
[0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5] 0.5

mar

mnar
Missing Rate 0.5

yacht_hydrodynamics 0.5
mcar
[0.5 0.5 0.5 0.5 0.5 0.5] 0.5

mar

mnar
Missing Rate 0.5

concrete_compression 0.5
mcar
[0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5] 0.5

mar

mnar
Missing Rate 0.5



In [108]:
import numpy as np

def missing_abnormal_check(mask, p):
    n, d = mask.shape  # Get the number of rows (n) and columns (d)
    m1 = int(p * n)  # Calculate the desired number of missing values per column

    for i in range(d):  # Iterate over each column
        m2 = np.sum(mask[:, i] == 0)  # Count the number of 0s in the column
        if m2 == n:
            excess = m2 - m1  # Calculate how many 0s need to be changed to 1s
            indices = np.where(mask[:, i] == 0)[0]  # Get indices of all 0s
            np.random.shuffle(indices)  # Randomly shuffle these indices
            indices_to_change = indices[:excess]  # Select the first 'excess' indices
            mask[indices_to_change, i] = 1  # Change these indices from 0 to 1

    return mask

## Missing Mechan

In [150]:
def MCAR(observed_values, p, seed=1):
    np.random.seed(seed)
    num_rows, num_cols = observed_values.shape
    num_to_remove_per_column = int(num_rows * p)
    masks = np.ones_like(observed_values)
    for col in range(num_cols):
        indices_to_remove = np.random.choice(num_rows, num_to_remove_per_column, replace=False)
        masks[indices_to_remove, col] = 0
    calculate_missing_rates(masks)
    return masks
def ensure_dir(directory):
    if not os.path.exists(directory):
        os.makedirs(directory)
def mask_recover(mask, p):
    n = mask.shape[0]  # Number of rows in the mask
    
    # Calculate the missing rate for each column
    missing_rate_per_column = np.mean(mask == 0, axis=0)
    
    # Calculate the necessary adjustments for each column to achieve the target missing rate p
    adjustment_needed = np.round((missing_rate_per_column - p) * n)

    # Modify the mask to approach the target missing rate p
    for i in range(mask.shape[1]):  # Iterate over each column
        if adjustment_needed[i] > 0:  # Too many zeros, need to convert some to ones
            zero_indices = np.where(mask[:, i] == 0)[0]
            np.random.seed(1)
            np.random.shuffle(zero_indices)  # Shuffle the zero indices
            recover_amount = int(min(adjustment_needed[i], len(zero_indices)))
            # Set the first 'recover_amount' shuffled indices to 1
            mask[zero_indices[:recover_amount], i] = 1
            

    return mask

In [130]:
def calculate_missing_rates(mask):
    # Calculate missing rate for each column
    num_rows, num_cols = mask.shape
    missing_rate_per_column = np.sum(mask == 0, axis=0) / num_rows

    # Calculate overall missing rate
    total_elements = num_rows * num_cols
    overall_missing_rate = np.sum(mask == 0) / total_elements

    print(np.round(missing_rate_per_column,5), np.round(overall_missing_rate,5))

In [159]:


def pick_coeffs(X, idxs_obs=None, idxs_nas=None, self_mask=False):
    n, d = X.shape
    if self_mask:
        torch.manual_seed(d)
        coeffs = torch.randn(d)
        Wx = X * coeffs
        coeffs /= torch.std(Wx, 0)
    else:
        d_obs = len(idxs_obs)
        d_na = len(idxs_nas)
        torch.manual_seed(d)
        coeffs = torch.randn(d_obs, d_na).float()

        # Dynamically adjust coeffs to match the type of X[:, idxs_obs]
        if X[:, idxs_obs].dtype == torch.double:
            coeffs = coeffs.double()
        # Add more conditions here if there are other types you need to handle

        # Perform operations
        Wx = X[:, idxs_obs].mm(coeffs)
        coeffs /= torch.std(Wx, 0, keepdim=True)
    return coeffs


def fit_intercepts(X, coeffs, p, self_mask=False):
    if self_mask:
        d = len(coeffs)
        intercepts = torch.zeros(d)
        for j in range(d):
            def f(x):
                return torch.sigmoid(X * coeffs[j] + x).mean().item() - p

            #intercepts[j] = optimize.bisect(f, -500, 500)
            try:
                
                intercepts[j] = optimize.bisect(f, -500, 500)
            except:
                pass
                #print("Fail inters")
                #print(f(-500),f(500))
    else:
        d_obs, d_na = coeffs.shape
        intercepts = torch.zeros(d_na)
        for j in range(d_na):
            def f(x):
                return torch.sigmoid(X.mv(coeffs[:, j]) + x).mean().item() - p

            #intercepts[j] = optimize.bisect(f, -500, 500)
            
            try:
                intercepts[j] = optimize.bisect(f, -500, 500)
            except:
                pass
                #print("Fail inters")
                #print(f(-500),f(500))       
    return intercepts


def MAR(X, p, p_obs = 0.5,seed = 1):

    n, d = X.shape

    to_torch = torch.is_tensor(X) ## output a pytorch tensor, or a numpy array
    if not to_torch:
        X = torch.from_numpy(X)

    mask = torch.zeros(n, d).bool() if to_torch else np.zeros((n, d)).astype(bool)

    d_obs = max(int(p_obs * d), 1) ## number of variables that will have no missing values (at least one variable)
    d_na = d - d_obs ## number of variables that will have missing values

    ### Sample variables that will all be observed, and those with missing values:
    np.random.seed(n)
    idxs_obs = np.random.choice(d, d_obs, replace=False)
    idxs_nas = np.array([i for i in range(d) if i not in idxs_obs])

    ### Other variables will have NA proportions that depend on those observed variables, through a logistic model
    ### The parameters of this logistic model are random.

    ### Pick coefficients so that W^Tx has unit variance (avoids shrinking)
    coeffs = pick_coeffs(X, idxs_obs, idxs_nas)
    ### Pick the intercepts to have a desired amount of missing values
    intercepts = fit_intercepts(X[:, idxs_obs], coeffs, p)

    ps = torch.sigmoid(X[:, idxs_obs].mm(coeffs) + intercepts)
    torch.manual_seed(n)
    ber = torch.rand(n, d_na)
    mask[:, idxs_nas] = 1- (ber < ps).int()
    mask = missing_abnormal_check(mask, p)
    #calculate_missing_rates(mask)

    return mask

#

def MNAR(X, p):
    print("Missing Rate",p)

    n, d = X.shape

    to_torch = torch.is_tensor(X) ## output a pytorch tensor, or a numpy array
    if not to_torch:
        X = torch.from_numpy(X)

    ### Variables will have NA proportions that depend on those observed variables, through a logistic model
    ### The parameters of this logistic model are random.

    ### Pick coefficients so that W^Tx has unit variance (avoids shrinking)
    coeffs = pick_coeffs(X, self_mask=True)
    
    ### Pick the intercepts to have a desired amount of missing values
    intercepts = fit_intercepts(X, coeffs, p, self_mask=True)
    

    ps = torch.sigmoid(X * coeffs + intercepts)


    np.random.seed(n)
    ber = np.random.rand(n, d)
    mask = 1-(ber < ps if to_torch else ber < ps.numpy()).astype(int)
    mask = missing_abnormal_check(mask, p)
    #calculate_missing_rates(mask)
    
    #mask = 1-mask
    return mask
