In [56]:
import os

import numpy as np

import pandas as pd

import json

In [77]:
data_list = ['banknote','california','climate_model_crashes','concrete_compression',
 'connectionist_bench_sonar','qsar_biodegradation','wine_quality_red','wine_quality_white','yacht_hydrodynamics',
 'yeast']
para = 0.5
type_list = ["diffuse","logistic","mar","mcar"]

In [83]:
data_list = ["banknote","climate_model_crashes","connectionist_bench_sonar","qsar_biodegradation","yeast"]
data_list = ['concrete_compression','wine_quality_red','wine_quality_white','yacht_hydrodynamics']
type_list =  ["diffuse","logistic","mar","mcar"]

for data in data_list:
    for types in type_list:
        path = '{}_{}/'.format(data,types)
        if not os.path.exists(path):
            os.makedirs(path)
        #ori = np.load('datasets/{}/{}_norm.npy'.format(data,data))
        X,y = load_data(data)
        
        mask = np.load('datasets/{}/{}/{}.npy'.format(data,types,0.3))

        with open('datasets/{}/split_index_seed-1.json'.format(data), 'r') as file:
            index = json.load(file)



        X[mask == 0] = np.nan

        train_index = index['train_index']
        test_index = index['test_index']

        # Split X and y into train and test sets
        X_train = X[train_index]
        X_test = X[test_index]
        y_train = y[train_index]
        y_test = y[test_index]

        np.savetxt(path+'train_data.txt', X_train, delimiter=',')
        np.savetxt(path+'test_data.txt', X_test, delimiter=',')
        np.savetxt(path+'train_labels.txt', y_train, delimiter=',')
        np.savetxt(path+'test_labels.txt', y_test, delimiter=',')

In [76]:
from sklearn.datasets import load_iris, load_wine, fetch_california_housing
from sklearn.preprocessing import LabelEncoder

# Assuming df is your DataFrame and the label column is 'target'


data_list = ['banknote','california','climate_model_crashes','concrete_compression',
 'connectionist_bench_sonar','qsar_biodegradation','wine_quality_red','wine_quality_white','yacht_hydrodynamics',
 'yeast']

def load_data(name):
    label_encoder = LabelEncoder()
    if name == 'banknote':
     with open('datasets/banknote/data_banknote_authentication.txt', 'rb') as f:
        df = pd.read_csv(f, low_memory=False, sep=',')
        X = df.values[:,:-1]
        y = df.values[:,-1]
        y = label_encoder.fit_transform(y)
    elif name == 'california':
        data  = fetch_california_housing()
        X = data["data"]
        y = data["target"]

    elif name == 'climate_model_crashes':
        X,y = fetch_climate_model_crashes()
        y = label_encoder.fit_transform(y)
    elif name == 'concrete_compression':
         X,y = fetch_concrete_compression()
    elif name == 'yacht_hydrodynamics':
         X,y = fetch_yacht_hydrodynamics()
    elif name == 'airfoil_self_noise':
         X,y = fetch_airfoil_self_noise()
    elif name == 'connectionist_bench_sonar':
         X,y = fetch_connectionist_bench_sonar()
         y = label_encoder.fit_transform(y) 
    elif name == 'qsar_biodegradation':
         X,y = fetch_qsar_biodegradation()
         y = label_encoder.fit_transform(y) 
    elif name == 'wine_quality_red':
             X,y = fetch_wine_quality_red()
    elif name == 'wine_quality_white':
             X,y = fetch_wine_quality_white() 
    elif name == 'yeast':
             X,y = fetch_yeast()
             y = label_encoder.fit_transform(y)  

    return X,y



In [54]:
data_list = ['banknote','california','climate_model_crashes','concrete_compression',
 'connectionist_bench_sonar','qsar_biodegradation','wine_quality_red','wine_quality_white','yacht_hydrodynamics',
 'yeast']
clf = ["banknote","climate_model_crashes","connectionist_bench_sonar","qsar_biodegradation","yeast"]

for name in data_list:
    load_data(name)

[[  3.6216    8.6661   -2.8073   -0.44699]
 [  4.5459    8.1674   -2.4586   -1.4621 ]
 [  3.866    -2.6383    1.9242    0.10645]
 ...
 [ -3.7503  -13.4586   17.5932   -2.7771 ]
 [ -3.5637   -8.3827   12.393    -1.2823 ]
 [ -2.5419   -0.65804   2.6842    1.1952 ]] [0 0 0 ... 1 1 1]
[[   8.3252       41.            6.98412698 ...    2.55555556
    37.88       -122.23      ]
 [   8.3014       21.            6.23813708 ...    2.10984183
    37.86       -122.22      ]
 [   7.2574       52.            8.28813559 ...    2.80225989
    37.85       -122.24      ]
 ...
 [   1.7          17.            5.20554273 ...    2.3256351
    39.43       -121.22      ]
 [   1.8672       18.            5.32951289 ...    2.12320917
    39.43       -121.32      ]
 [   2.3886       16.            5.25471698 ...    2.61698113
    39.37       -121.24      ]] [4.526 3.585 3.521 ... 0.923 0.847 0.894]
[[0.85903621 0.92782454 0.25286562 ... 0.85831037 0.79699724 0.86989304]
 [0.60604103 0.45772836 0.35944842 ... 0

In [39]:
def fetch_climate_model_crashes():
    with open('datasets/climate_model_crashes/pop_failures.dat', 'rb') as f:
        df = pd.read_csv(f, delimiter='\s+', header = 0)
        # Ignore the two blocking factor
        X = df.values[:, 2:-1]
        y =  df.values[:, -1]

    return X,y

def fetch_concrete_compression():
    with open('datasets/concrete_compression/Concrete_Data.xls', 'rb') as f:
        df = pd.read_excel(io=f)
        X = df.values[:, :-1]
        y =  df.values[:, -1]
    return X,y


def fetch_yacht_hydrodynamics():
    with open('datasets/yacht_hydrodynamics/yacht_hydrodynamics.data', 'rb') as f:
        df = pd.read_csv(f, delimiter='\s+', header = None)
        X = df.values[:, :-1]
        y =  df.values[:, -1]
    return X,y


def fetch_connectionist_bench_sonar():
    with open('datasets/connectionist_bench_sonar/sonar.all-data', 'rb') as f:
        df = pd.read_csv(f, delimiter=',', header = None)

        X = df.values[:, :-1].astype('float')
        y =  df.values[:, -1]
    return X,y


def fetch_qsar_biodegradation():
    with open('datasets/qsar_biodegradation/biodeg.csv', 'rb') as f:
        df = pd.read_csv(f, delimiter=';', header = None)
        X = df.values[:, :-1].astype('float')
        y =  df.values[:, -1]

    return X,y

def fetch_yeast():
    with open('datasets/yeast/yeast.data', 'rb') as f:
        df = pd.read_csv(f, delimiter='\s+', header = None)
        X = df.values[:, 1:-1].astype('float')
        y =  df.values[:, -1]

    return X,y


def fetch_wine_quality_red():
    with open('datasets/wine_quality_red/winequality-red.csv', 'rb') as f:
        df = pd.read_csv(f, delimiter=';')
        X = df.values[:, :-1].astype('float')
        y =  df.values[:, -1]
    return X,y

# Dpne!
def fetch_wine_quality_white():
    with open('datasets/wine_quality_white/data.csv', 'rb') as f:
        df = pd.read_csv(f, delimiter=';')
        X = df.values[:, :-1].astype('float')
        y =  df.values[:, -1]
    return X,y


In [80]:
from sklearn.datasets import load_digits
from sklearn.decomposition import KernelPCA
X, _ = load_digits(return_X_y=True)
transformer = KernelPCA(n_components=7, kernel='linear')
X_transformed = transformer.fit_transform(X)
X_transformed.shape

(1797, 7)